export { default as Editor } from './editor'
export { default as Logo } from './logo'
export { default as CommentPost } from './Comment'
export { default as HighLightGroup } from './HighlightGroup'
export { default as HighLightPost } from './HighlightPost'
export { default as ModalCreatePost } from './ModalCreatePost'
export { default as SharePost } from './SharePost'
export { default as ModalReport } from './ModalReport'
export { default as Reaction } from './reaction'
export { default as InputCustome } from './inputCustome'
// export { default as ActionPost } from './actionPost'
